_MONGODB_USER = 'root'
_MONGODB_PASSWD = '123456'
_MONGODB_HOST = '127.0.0.1:27017'
_MONGODB_NAME = 'flvis'
_MONGODB_DATABASE_HOST = \
    'mongodb://%s:%s@%s/%s' \
    % (_MONGODB_USER, _MONGODB_PASSWD, _MONGODB_HOST, _MONGODB_NAME)